[package]
name = "glium"
version = "0.2.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "High-level and safe OpenGL wrapper."
keywords = ["opengl", "gamedev"]
documentation = "http://tomaka.github.io/glium/glium/index.html"
homepage = "http://tomaka.github.io/glium"
repository = "https://github.com/tomaka/glium"
license = "Apache-2.0"
build = "build/main.rs"
exclude = ["doc", ".travis.yml", "circle.yml"]

[features]
default = ["image", "nalgebra", "cgmath", "gl_read_buffer", "gl_depth_textures"]
gl_read_buffer = []
gl_uniform_blocks = []
gl_sync = []
gl_persistent_mapping = ["gl_sync"]
gl_program_binary = []
gl_tessellation = []
gl_instancing = []
gl_integral_textures = []
gl_depth_textures = []
gl_stencil_textures = []
gl_texture_1d = []
gl_texture_3d = []
gl_texture_multisample = []
gl_texture_multisample_array = []
headless = ["glutin/headless"]

[dependencies.glutin]
version = "*"
features = ["window"]

[dependencies.cgmath]
version = "*"
optional = true

[dependencies.nalgebra]
version = "*"
optional = true

[dependencies.image]
version = "*"
optional = true

[dependencies]
gl_common = "*"
libc = "*"

[build-dependencies]
gl_generator = "*"
khronos_api = "*"

[dev-dependencies]
clock_ticks = "*"
genmesh = "*"
obj = "*"
rand = "*"
